### ISSUE TITLE
Binary builds with no source code

### ISSUE THREAD

**Issue by lukefor** [republicprotocol/republic-go#110]
Binary builds of this repo are being shipped as releases on https://github.com/republicprotocol/darknode-cli/releases. The source code attached to each release is of the `darknode-cli` repo, but the binary is from this `republic-go` repo.

Where can the source code for these updates be found?

**Comment by loongy** [comment]
See https://github.com/republicprotocol/darknode-cli/issues/19.

**Comment by lukefor** [comment]
That is not compatible with the GPL license...

**Comment by loongy** [comment]
> That is not compatible with the GPL license...
> **lukefor**

That private repo isn’t under the GPL license yet. This repo is, but it’s not used by any of our private repos.

(EDIT: you have since deleted your comment, but I’m quoting it here for continuity for others that might be curious about this topic.)

**Comment by lukefor** [comment]
So you're saying that the private darknode-go repo is a cleanroom implementation? 

To comply with GPL you can't use any of this repo's code whatsoever in your private repo and closed-source builds

**Comment by loongy** [comment]
> So you're saying that the private darknode-go repo is a cleanroom implementation?
> 
> To comply with GPL you can't use any of this repo's code whatsoever in your private repo and closed-source builds
> **lukefor**

That’s not actually true. See https://www.gnu.org/licenses/gpl-faq.html#GPLRequireSourcePostedPublic. Furthermore, copyright holders are not bound by open source licenses that they distribute their own work under.

But, this repo itself is not used by the newer Darknode repo that implements RenVM and its new networking layer.

(EDIT: you have since deleted your comment, but I’m quoting it here for continuity for others that might be curious about this topic.)

**Comment by lukefor** [comment]
Yes my misunderstanding of the license, you are ok if you are the copyright holder of all GPL libraries/code involved. That is the only reason you're covered though, you couldn't ship binaries otherwise (as per your link)

(EDIT: Yikes that's creepy quoting deleted posts)
